package com.oauth.labapi.utils;

public enum EventsF {


    DEPOT_FACTURE("DEPOT FACTURE PAR FOURNISSEUR"),
    ST_VALIDATION_DU_SERVICE_FAIT("VALIDATION DU SERVICE FAIT"),
    ST_REJET_DU_SERVICE_FAIT("REJET_DU SERVICE FAIT"),
    ST_SATISFACTION_DU_SERVICE_FAIT("SATISFACTION DU SERVICE FAIT"),
    ST_REJET_DU_SERVICE_FAIT_SAT("REJET DU SERVICE FAIT"),
    ST_SATISFACTION_DU_SERVICE_FAIT_SAT("SATISFACTION DU SERVICE FAIT"),
    SM_EMISSION_DE_DOSSIER_DE_PAIEMENT("S.M EMISSION DE DOSSIER DE PAIEMENT"),
    REJET_DOSSIER_DE_PAIEMENT_TECHNIQUE("REJET DOSSIER DE PAIEMENT (TECHNIQUE)"),
    SM_REJET_DOSSIER_DE_PAIEMENT_FOURNISSEUR ("REJET DOSSIER DE PAIEMENT (FOURNISSEUR)"),
    FRNS_SATISFACTION_DU_REJET_DU_DOSSIER_DE_PAIEMENT("FRNSR SATISFACTION DU REJET DU DOSSIER DE PAIEMENT"),
    ST_SATISFACTION_DU_REJET_DU_DOSSIER_DE_PAIEMENT("ST SATISFACTION DU REJET DU DOSSIER DE PAIEMENT"),
    ORDONNANCEMENT_DU_DOSSIER_DE_PAIEMENT("ORDONNANCEMENT DU DOSSIER DE PAIEMENT"),
    SATISFACTION_DU_REJET_DE_ORDONNANCEMENT("SATISFACTION DU REJET DE L ORDONNANCEMENT"),
    REJET_DOSSIER_DE_PAIEMENT_FOURNISSEUR("REJET DOSSIER DE PAIEMENT (FOURNISSEUR)"),
    PAIEMENT("PAIEMENT"),
    REJET_DE_PAIEMENT("REJET DE PAIEMENT"),
    SATISFACTION_REJET_DE_PAIEMENT("SATISFACTION REJET DE PAIEMENT"),
    REJET_DE_ORDONNANCMENT("REJET DE L ORDONNANCMENT"),
    ST_REJET_DU_SERVICE_FAIT_ST(""),
    ST_SATISFACTION_DU_SERVICE_FAIT_RS("rejet to satisfaction");

    private String description;

    private EventsF(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }
}